[package]
name = "noclist"
version = "0.1.0"
edition = "2018"
 
[dependencies]
tokio = { version = "1.8.1", features = ["full"] }
reqwest = { version = "0.11.4", features = ["json"] }
serde_json = "1.0.64"
sha2 = "0.9.5"
hex = "0.4.3"

[[bin]]
name = "noclist"
path = "bin/main.rs"
